version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "123456" ]
    environment:
      - REDIS_PASSWORD=123456
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
